# -*- coding: utf-8 -*-
"""01_hello_world.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10100hlasP9drKgLIcxlDgSRTkkQg0snA

"Hello world" en Python
===
Cuando los programadores aprendemos un nuevo idioma, solemos escribir un programa de una línea que imprime una versión del mensaje "¡Hola mundo!" este es un programa simple que muestra si tu computadora está configurada correctamente para ejecutar programas de Python.
"""

print('Hello Python World!')

print("Hello Data Science!")