# -*- coding: utf-8 -*-
"""02_expressions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h1RrC6Rp0ES8yUHiVwdwTsDJFK4I0kYq

# Expresiones Numéricas
"""

2016

2000 + 16

1 + 2 * ((3 * 4 * 5 // 6) ** 3) + 7 + 8

"""# Call Expressions"""

max(3, 4.5)

pow(100, 2)

pow(2, 100)

max(1, -2, 3, -4)

max(pow(10, 2), pow(2, 10), 1010)

"""# Importar librerías y aritmética con call expressions"""

from operator import add, mul

add(1, 2)

mul(4, 6)

mul(add(4, mul(4, 6)), add(3, 5))

mul(9, mul(add(4, mul(4, 6)), add(3, 5)))