# -*- coding: utf-8 -*-
"""04_if_statements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jiZzf90wwBlYokXHZ07Y93CbTKYj1gdl

Declaraciones *if*
===
Al permitirle responder de manera selectiva a diferentes situaciones y condiciones, los "if" abren nuevas posibilidades para sus programas. En esta sección, aprenderemos cómo probar ciertas condiciones y luego responder de manera adecuada a esas condiciones.

¿Qué es una declaración *if*?
===
Una declaración *if* prueba una condición y luego responde a esa condición. Si la condición es verdadera, entonces cualquier acción que se enumere a continuación se lleva a cabo. Puedes probar múltiples condiciones al mismo tiempo y responder adecuadamente a cada condición.

Ejemplo
---
Aquí hay un ejemplo que muestra una serie de postres que me gustan. Se pueden enumerar esos postres, pero te permite saber cuál es mi favorito.
"""

# A list of desserts I like.
desserts = ['helado', 'chocolate', 'caramelo', 'galleta']
favorite_dessert = 'caramelo'

# Print the desserts out, but let everyone know my favorite dessert.
for dessert in desserts:
    if dessert == favorite_dessert:
        # This dessert is my favorite, let's let everyone know!
        print("¡El %s es mi postre favorito!" % dessert.title())
    else:
        # I like these desserts, but they are not my favorite.
        print("Quiero %s." % dessert)

"""#### ¿Qué pasa en este programa?

- El programa comienza con una lista de postres, y un postre se identifica como favorito.
- El bucle for recorre todos los postres.
- Dentro del bucle for, se prueba cada elemento de la lista.
     - Si el valor actual de *dessert* es igual al valor de *favorite_dessert*, se imprime un mensaje de que este es mi favorito.
     - Si el valor actual de *dessert* no es igual al valor de *favorite_dessert*, se imprime un mensaje que simplemente me gusta el postre.
    
Puedes probar tantas condiciones como desees en una sentencia *if*, como verás en un momento.

Pruebas logicas
===
Cada sentencia if se evalúa como *True* o *False*. *True* y *False* son palabras clave de Python, que tienen significados especiales adjuntos. Puedes probar las siguientes condiciones en sus declaraciones if:

- igualdad (==)
- desigualdad (! =)
- otras desigualdades
     - mayor que (>)
     - mayor que o igual a (> =)
     - menos que (<)
     - menor o igual que (<=)
- Puede probar si un elemento está **en** una lista.

Igualdad
---
Dos elementos son *iguales* si tienen el mismo valor. Puedes probar la igualdad entre números, cadenas y una cantidad de otros objetos que aprenderá más adelante. Algunos de estos resultados pueden ser sorprendentes, así que observa detenidamente los ejemplos a continuación.

En Python, como en muchos lenguajes de programación, dos pruebas de signos de igualdad equivalen.

**¡Ten cuidado!** de no usar accidentalmente un signo de igual, lo que realmente puede hacer que las cosas salgan mal porque ese signo de igual pone su item al valor que está probando.
"""

5 == 5

3 == 5

5 == 5.0

'favio' == 'favio'

'Pedro' == 'pedro'

'Carlos'.lower() == 'carlos'.lower()

'5' == 5

'5' == str(5)

"""Desigualdad
---
Dos elementos son *desigual* si no tienen el mismo valor. En Python, probamos la desigualdad usando el signo de exclamación y uno es el signo igual.

A veces quieres probar la igualdad y si eso falla, asume la desigualdad. A veces tiene más sentido probar directamente la desigualdad.
"""

3 != 5

5 != 5

'Favio' != 'Favio'

"""Otras desigualdades
---
### Más grande que
"""

5 > 3

"""### Mayor or igual que"""

5 >= 3

3 >= 3

"""### Menor que"""

3 < 5

"""### Menor o igual que"""

3 <= 5

3 <= 3

"""Comprobando si un artículo es **en** una lista
---
Puedes verificar si un elemento está en una lista usando la palabra clave **in**.
"""

vowels = ['a', 'e', 'i', 'o', 'u']
'a' in vowels

vowels = ['a', 'e', 'i', 'o', 'u']
if 'a' in vowels:
    print("hello")

"""Ejercicios
---
#### Verdadero y falso
- Escribe un programa que conste de al menos diez líneas, cada una de las cuales tiene una declaración lógica. La salida de su programa debe ser 5 **True** y 5 ** False **.
- Nota: probablemente necesitarás escribir `print (5> 3)`, no solo `5> 3`.

La cadena if-elif ... else
===
Puedes probar cualquier serie de condiciones que desee y puede probar sus condiciones en cualquier combinación que desee.

Simples declaraciones *if*
---
La prueba más simple tiene una única instrucción **if**, y una única instrucción para ejecutar si la condición es **True**.
"""

dogs = ['willie', 'hootz', 'peso', 'juno']

if len(dogs) > 3:
    print("Wow, we have a lot of dogs here!")

"""En esta situación, no pasa nada si la prueba no pasa."""

dogs = ['willie', 'hootz']

if len(dogs) > 3:
    print("Wow, we have a lot of dogs here!")

"""Ten en cuenta que no hay errores. La condición `len (dogs)> 3` se evalúa como False, y el programa pasa a cualquier línea después del bloque **if**.

Declaraciones if-else
---
Muchas veces querrás responder de dos maneras posibles a una prueba. Si la prueba se evalúa como **True**, desearás hacer una cosa. Si la prueba se evalúa como **False**, querrás hacer otra cosa. La estructura **if-else** te permite hacerlo fácilmente.
"""

dogs = ['willie', 'hootz', 'peso', 'juno']

if len(dogs) > 3:
    print("Wow, we have a lot of dogs here!")
else:
    print("Okay, this is a reasonable number of dogs.")

"""Nuestros resultados no han cambiado en este caso, porque si la prueba se evalúa como **True** solo se ejecutan las declaraciones bajo la instrucción **if**. Las declaraciones en el área **else** solo se ejecutan si la prueba falla:"""

dogs = ['willie', 'hootz']

if len(dogs) > 3:
    print("Wow, we have a lot of dogs here!")
else:
    print("Okay, this is a reasonable number of dogs.")

"""La prueba se evaluó a **False**, por lo que solo se ejecuta la instrucción bajo `else`.

Cadenas if-elif ... else 
---
Muchas veces, querrás probar una serie de condiciones, en lugar de solo una situación o cualquiera de ellas. Puedes hacer esto con una serie de sentencias if-elif-else

No hay límite a la cantidad de condiciones que puede probar. Siempre necesitas una sentencia if para iniciar la cadena, y nunca puede tener más de una sentencia. Pero puedes tener tantas declaraciones elif como quieras.
"""

dogs = ['willie', 'hootz', 'peso', 'monty', 'juno', 'turkey']

if len(dogs) >= 5:
    print("Holy mackerel, we might as well start a dog hostel!")
elif len(dogs) >= 3:
    print("Wow, we have a lot of dogs here!")
else:
    print("Okay, this is a reasonable number of dogs.")

"""Es importante tener en cuenta que en situaciones como esta, solo se evalúa la primera prueba. En una cadena if-elif-else, una vez que una prueba pasa, el resto de las condiciones se ignoran."""

dogs = ['willie', 'hootz', 'peso', 'monty']

if len(dogs) >= 5:
    print("Holy mackerel, we might as well start a dog hostel!")
elif len(dogs) >= 3:
    print("Wow, we have a lot of dogs here!")
else:
    print("Okay, this is a reasonable number of dogs.")

"""La primera prueba falló, por lo que Python evaluó la segunda prueba. Esa prueba fue aprobada, por lo que se ejecuta la instrucción correspondiente a `len (dogs)> = 3`."""

dogs = ['willie', 'hootz']

if len(dogs) >= 5:
    print("Holy mackerel, we might as well start a dog hostel!")
elif len(dogs) >= 3:
    print("Wow, we have a lot of dogs here!")
else:
    print("Okay, this is a reasonable number of dogs.")

"""En esta situación, las dos primeras pruebas fallan, por lo que se ejecuta la instrucción en la cláusula else. Ten en cuenta que esta declaración se ejecutaría incluso si no hay ningún perro:"""

dogs = []

if len(dogs) >= 5:
    print("Holy mackerel, we might as well start a dog hostel!")
elif len(dogs) >= 3:
    print("Wow, we have a lot of dogs here!")
else:
    print("Okay, this is a reasonable number of dogs.")

"""Ten en cuenta que no tiene que realizar ninguna acción al iniciar una serie de sentencias if. Simplemente no puede hacer nada en la situación de que no haya perros reemplazando la cláusula `else` con otra cláusula` elif`:"""

dogs = []

if len(dogs) >= 5:
    print("Holy mackerel, we might as well start a dog hostel!")
elif len(dogs) >= 3:
    print("Wow, we have a lot of dogs here!")
elif len(dogs) >= 1:
    print("Okay, this is a reasonable number of dogs.")

"""En este caso, solo imprimimos un mensaje si hay al menos un perro presente. Por supuesto, puedes agregar una nueva cláusula `else` para responder a la situación en la que no hay perros:"""

dogs = []

if len(dogs) >= 5:
    print("Holy mackerel, we might as well start a dog hostel!")
elif len(dogs) >= 3:
    print("Wow, we have a lot of dogs here!")
elif len(dogs) >= 1:
    print("Okay, this is a reasonable number of dogs.")
else:
    print("I wish we had a dog here.")

"""Como puedes ver, la cadena if-elif-else te permite responder de manera muy específica a cualquier situación dada.

Ejercicios
---
#### Tres es una multitud
- Haz una lista de nombres que incluya al menos cuatro personas.
- Escribe una prueba de if que imprima un mensaje sobre la sala llena de gente si hay más de tres personas en su lista.
- Modifica tu lista para que solo haya dos personas en ella. Usa uno de los métodos para eliminar personas de la lista, no solo redefina la lista.
- Ejecute tu prueba de nuevo. No debería haber salida esta vez, porque hay menos de tres personas en la lista.

#### Tres es una multitud - Parte 2
- Guarda tu programa de * Tres es una multitud * con un nuevo nombre.
- Agrega una declaración `else` a tus pruebas if. Si se ejecuta la instrucción `else`, pídele que imprima un mensaje que indique que la sala no está muy llena.

#### Seis es una mafia
- Guarda su programa de * Tres es una multitud - Parte 2 * con un nuevo nombre.
- Agrega algunos nombres a su lista, de modo que haya al menos seis personas en la lista.
- Modifica tus pruebas para que
    - Si hay más de 5 personas, se imprime un mensaje que indica que hay una mafia en la sala.
    - Si hay 3-5 personas, se imprime un mensaje sobre la sala llena de gente.
    - Si hay 1 o 2 personas, se imprime un mensaje acerca de que la habitación no está llena.
    - Si no hay personas en la habitación, se imprime un mensaje en la habitación que está vacía.

Más de una prueba que pasa
===
En todos los ejemplos que hemos visto hasta ahora, solo una prueba puede pasar. Tan pronto como la primera prueba pasa, el resto de las pruebas se ignoran. Esto es realmente bueno, porque permite que nuestro código se ejecute de manera más eficiente. Muchas veces, solo una condición puede ser verdadera, por lo que probar cada condición después de una pasada no tendría sentido.

Hay situaciones en las que desea ejecutar una serie de pruebas, donde se ejecuta cada prueba individual. Estas son situaciones en las que cualquiera o todas las pruebas podrían pasar, y usted quiere responder a cada prueba que pasa. Consideremos el siguiente ejemplo, donde queremos saludar a cada perro que está presente:
"""

dogs = ['willie', 'hootz']

if 'willie' in dogs:
    print("Hello, Willie!")
if 'hootz' in dogs:
    print("Hello, Hootz!")
if 'peso' in dogs:
    print("Hello, Peso!")
if 'monty' in dogs:
    print("Hello, Monty!")

"""Si hubiéramos hecho esto utilizando una cadena if-elif-else, solo se saludaría al primer perro que esté presente:"""

dogs = ['willie', 'hootz']

if 'willie' in dogs:
    print("Hello, Willie!")
elif 'hootz' in dogs:
    print("Hello, Hootz!")
elif 'peso' in dogs:
    print("Hello, Peso!")
elif 'monty' in dogs:
    print("Hello, Monty!")

"""Por supuesto, esto podría escribirse de forma mucho más limpia utilizando listas y para bucles."""

dogs_we_know = ['willie', 'hootz', 'peso', 'monty', 'juno', 'turkey']
dogs_present = ['willie', 'hootz']

# Go through all the dogs that are present, and greet the dogs we know.
for dog in dogs_present:
    if dog in dogs_we_know:
        print("Hello, %s!" % dog.title())

"""Este es el tipo de código que deberías escribir. Está bien idear un código que sea menos eficiente al principio. Cuando te des cuenta de que está escribiendo repetidamente el mismo tipo de código en un programa, mira si puede usar un bucle o una función para hacer que su código sea más eficiente.

Valores verdaderos y falsos
===
Cada valor puede ser evaluado como Verdadero o Falso. La regla general es que cualquier valor distinto de cero o no vacío se evaluará como Verdadero. Si alguna vez no estás seguro, puede abrir un terminal de Python y escribir dos líneas para averiguar si el valor que estás considerando es Verdadero o Falso. Mira los siguientes ejemplos, tenlos en cuenta y prueba cualquier valor que te interese.
"""

if 0:
    print("This evaluates to True.")
else:
    print("This evaluates to False.")

if 1:
    print("This evaluates to True.")
else:
    print("This evaluates to False.")

# Arbitrary non-zero numbers evaluate to True.
if 1253756:
    print("This evaluates to True.")
else:
    print("This evaluates to False.")

# Negative numbers are not zero, so they evaluate to True.
if -1:
    print("This evaluates to True.")
else:
    print("This evaluates to False.")

# An empty string evaluates to False.
if '':
    print("This evaluates to True.")
else:
    print("This evaluates to False.")

# Any other string, including a space, evaluates to True.
if ' ':
    print("This evaluates to True.")
else:
    print("This evaluates to False.")

# Any other string, including a space, evaluates to True.
if 'hello':
    print("This evaluates to True.")
else:
    print("This evaluates to False.")

# None is a special object in Python. It evaluates to False.
if None:
    print("This evaluates to True.")
else:
    print("This evaluates to False.")